language: python
python:
  - "2.7"
notifications:
  email: false
install: "pip install -r requirements.txt"
script: 
    - py.test grapher/tests/TestNode.py -v
    - py.test grapher/tests/TestGraph.py -v
    - py.test grapher/tests/TestEdge.py -v
    - py.test grapher/tests/TestCycles.py -v
    - py.test grapher/tests/TestTranslator.py -v
