language: python
python:
  - "2.7"
notifications:
  email: false
install: "pip install -r requirements.txt"
script: 
    - py.test grapher/TestNode.py -v
    - py.test grapher/TestGraph.py -v
    - py.test grapher/TestEdge.py -v
    - py.test grapher/TestCycles.py -v
    - py.test grapher/TestTranslator.py -v
